{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lsh.plugin",
    "module": "superplugin",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "classGuard-1.1.jar",
          "url": "classGuard-1.1.jar",
          "size": 40038,
          "sha512": "5ac5f4c2029e131c9220a4fb6cafa4263481d0075f77adab9ddda7b3781b749a67e70c3571d0789a9ce9c978fd6f3b142b0fdd5351b3bce2f0b7f5ae5ea24dbf",
          "sha256": "8b9c865071af0622d8f68318501babaa79f5225be0b305e11ec31a32620b71cc",
          "sha1": "5052cdad4077327fb5e7f34961ac5b85580fc69f",
          "md5": "cc5dc7f26cbb7e2cd09b1345d2afe2e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "classGuard-1.1.jar",
          "url": "classGuard-1.1.jar",
          "size": 40038,
          "sha512": "5ac5f4c2029e131c9220a4fb6cafa4263481d0075f77adab9ddda7b3781b749a67e70c3571d0789a9ce9c978fd6f3b142b0fdd5351b3bce2f0b7f5ae5ea24dbf",
          "sha256": "8b9c865071af0622d8f68318501babaa79f5225be0b305e11ec31a32620b71cc",
          "sha1": "5052cdad4077327fb5e7f34961ac5b85580fc69f",
          "md5": "cc5dc7f26cbb7e2cd09b1345d2afe2e6"
        }
      ]
    }
  ]
}
